// frontend/src/components/ChallengeCard.jsx
import { Link } from 'react-router-dom'
import styles from './ChallengeCard.module.css'

function formatDate(iso) {
  if (!iso) return ''
  return new Date(iso).toLocaleDateString('it-IT', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })
}

export default function ChallengeCard({ challenge }) {
  return (
    <Link to={`/sfide/${challenge.id}`} className={`card card-hover ${styles.card}`}>
      <div className={styles.head}>
        <span className={styles.tag}>/regex/</span>
        <span className="muted" style={{ fontSize: '0.8rem' }}>
          {formatDate(challenge.createdAt)}
        </span>
      </div>
      <h3 className={styles.title}>{challenge.title}</h3>
      {challenge.description && <p className={styles.desc}>{challenge.description}</p>}
      <div className={styles.meta}>
        <span className="muted">
          di <strong className="accent">{challenge.authorUsername}</strong>
        </span>
      </div>
      <div className={styles.stats}>
        <span>🎯 {challenge.totalAttempts} tentativi</span>
        <span>✅ {challenge.solvedByCount} risolta</span>
      </div>
    </Link>
  )
}

// frontend/src/app/shared/challenge-card/challenge-card.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Challenge } from '../../core/api/challenges-api.service';

@Component({
  selector: 'app-challenge-card',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './challenge-card.component.html',
  styleUrl: './challenge-card.component.css',
})
export class ChallengeCardComponent {
  @Input({ required: true }) challenge!: Challenge;

  formatDate(iso: string): string {
    if (!iso) return '';
    return new Date(iso).toLocaleDateString('it-IT', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    });
  }
}

<a [routerLink]="['/sfide', challenge.id]" class="card card-hover">
  <div class="head">
    <span class="tag">/regex/</span>
    <span class="muted" style="font-size: 0.8rem">{{ formatDate(challenge.createdAt) }}</span>
  </div>
  <h3 class="title">{{ challenge.title }}</h3>
  <p class="desc" *ngIf="challenge.description">{{ challenge.description }}</p>
  <div class="meta">
    <span class="muted">di <strong class="accent">{{ challenge.authorUsername }}</strong></span>
  </div>
  <div class="stats">
    <span>🎯 {{ challenge.totalAttempts }} tentativi</span>
    <span>✅ {{ challenge.solvedByCount }} risolta</span>
  </div>
</a>
