// frontend/src/app/navbar/navbar.component.ts
import { CommonModule } from '@angular/common';
import { Component, HostListener, ElementRef, inject, signal } from '@angular/core';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { ThemeService } from '../core/theme.service';
import { AvatarComponent } from '../shared/avatar/avatar.component';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, AvatarComponent],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css',
})
export class NavbarComponent {
  private router = inject(Router);
  private elementRef = inject(ElementRef);

  auth = inject(AuthService);
  themeService = inject(ThemeService);

  menuOpen = signal(false);
  dropdownOpen = signal(false);

  // Chiude il dropdown cliccando fuori.
  @HostListener('document:mousedown', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    const dropdown = this.elementRef.nativeElement.querySelector('[data-user-menu]');
    if (dropdown && !dropdown.contains(event.target as Node)) {
      this.dropdownOpen.set(false);
    }
  }

  toggleMenu(): void {
    this.menuOpen.update((o) => !o);
  }

  closeMenu(): void {
    this.menuOpen.set(false);
  }

  toggleDropdown(): void {
    this.dropdownOpen.update((o) => !o);
  }

  handleLogout(): void {
    this.auth.logout();
    this.dropdownOpen.set(false);
    this.closeMenu();
    this.router.navigate(['/']);
  }
}

<nav class="navbar">
  <div class="container">
    <div class="inner">
      <a routerLink="/" class="logo" (click)="closeMenu()">
        Regex<span class="logoMark">Riddle</span>
      </a>

      <button
        class="hamburger"
        aria-label="Apri il menu"
        [attr.aria-expanded]="menuOpen()"
        (click)="toggleMenu()"
      >
        <span></span>
        <span></span>
        <span></span>
      </button>

      <div class="menu" [class.menuClosed]="!menuOpen()">
        <div class="links">
          <a routerLink="/sfide" routerLinkActive="linkActive" class="link" (click)="closeMenu()">Sfide</a>
          <a routerLink="/classifica" routerLinkActive="linkActive" class="link" (click)="closeMenu()">Classifica</a>
          <a routerLink="/come-funziona" routerLinkActive="linkActive" class="link" (click)="closeMenu()">Come funziona</a>
        </div>

        <div class="actions">
          <button
            class="iconButton"
            (click)="themeService.toggleTheme()"
            [attr.aria-label]="themeService.theme() === 'dark' ? 'Passa al tema chiaro' : 'Passa al tema scuro'"
            [title]="themeService.theme() === 'dark' ? 'Tema chiaro' : 'Tema scuro'"
          >
            {{ themeService.theme() === 'dark' ? '☀️' : '🌙' }}
          </button>

          <ng-container *ngIf="auth.isAuthenticated(); else guestLinks">
            <div class="userMenu" data-user-menu>
              <button
                class="userButton"
                (click)="toggleDropdown()"
                aria-haspopup="true"
                [attr.aria-expanded]="dropdownOpen()"
              >
                <app-avatar [username]="auth.user()?.username" [avatarUrl]="auth.user()?.avatarUrl" [size]="28" />
                <span class="userName">{{ auth.user()?.username }}</span>
              </button>
              <div class="dropdown" *ngIf="dropdownOpen()">
                <a routerLink="/profilo" class="dropdownItem" (click)="dropdownOpen.set(false); closeMenu()">
                  Profilo
                </a>
                <button class="dropdownItem" (click)="handleLogout()">Esci</button>
              </div>
            </div>
          </ng-container>
          <ng-template #guestLinks>
            <a routerLink="/login" class="btn btn-ghost btn-sm" (click)="closeMenu()">Accedi</a>
            <a routerLink="/registrati" class="btn btn-primary btn-sm" (click)="closeMenu()">Registrati</a>
          </ng-template>
        </div>
      </div>
    </div>
  </div>
</nav>

// frontend/src/components/Navbar.jsx
import { useEffect, useRef, useState } from 'react'
import { Link, NavLink, useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { useTheme } from '../hooks/useTheme'
import Avatar from './Avatar'
import styles from './Navbar.module.css'

export default function Navbar() {
  const { isAuthenticated, user, logout } = useAuth()
  const { theme, toggleTheme } = useTheme()
  const navigate = useNavigate()
  const [menuOpen, setMenuOpen] = useState(false)
  const [dropdownOpen, setDropdownOpen] = useState(false)
  const dropdownRef = useRef(null)

  // Chiude il dropdown cliccando fuori.
  useEffect(() => {
    function handleClick(e) {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target)) {
        setDropdownOpen(false)
      }
    }
    document.addEventListener('mousedown', handleClick)
    return () => document.removeEventListener('mousedown', handleClick)
  }, [])

  const closeMenu = () => setMenuOpen(false)

  const handleLogout = () => {
    logout()
    setDropdownOpen(false)
    closeMenu()
    navigate('/')
  }

  const navLinkClass = ({ isActive }) =>
    isActive ? `${styles.link} ${styles.linkActive}` : styles.link

  return (
    <nav className={styles.navbar}>
      <div className="container">
        <div className={styles.inner}>
          <Link to="/" className={styles.logo} onClick={closeMenu}>
            Regex<span className={styles.logoMark}>Riddle</span>
          </Link>

          <button
            className={styles.hamburger}
            aria-label="Apri il menu"
            aria-expanded={menuOpen}
            onClick={() => setMenuOpen((o) => !o)}
          >
            <span />
            <span />
            <span />
          </button>

          <div className={`${styles.menu} ${menuOpen ? '' : styles.menuClosed}`}>
            <div className={styles.links}>
              <NavLink to="/sfide" className={navLinkClass} onClick={closeMenu}>
                Sfide
              </NavLink>
              <NavLink to="/classifica" className={navLinkClass} onClick={closeMenu}>
                Classifica
              </NavLink>
              <NavLink to="/come-funziona" className={navLinkClass} onClick={closeMenu}>
                Come funziona
              </NavLink>
            </div>

            <div className={styles.actions}>
              <button
                className={styles.iconButton}
                onClick={toggleTheme}
                aria-label={theme === 'dark' ? 'Passa al tema chiaro' : 'Passa al tema scuro'}
                title={theme === 'dark' ? 'Tema chiaro' : 'Tema scuro'}
              >
                {theme === 'dark' ? '☀️' : '🌙'}
              </button>

              {isAuthenticated ? (
                <div className={styles.userMenu} ref={dropdownRef}>
                  <button
                    className={styles.userButton}
                    onClick={() => setDropdownOpen((o) => !o)}
                    aria-haspopup="true"
                    aria-expanded={dropdownOpen}
                  >
                    <Avatar username={user?.username} avatarUrl={user?.avatarUrl} size={28} />
                    {user?.username}
                  </button>
                  {dropdownOpen && (
                    <div className={styles.dropdown}>
                      <Link
                        to="/profilo"
                        className={styles.dropdownItem}
                        onClick={() => {
                          setDropdownOpen(false)
                          closeMenu()
                        }}
                      >
                        Profilo
                      </Link>
                      <button className={styles.dropdownItem} onClick={handleLogout}>
                        Esci
                      </button>
                    </div>
                  )}
                </div>
              ) : (
                <>
                  <Link to="/login" className="btn btn-ghost btn-sm" onClick={closeMenu}>
                    Accedi
                  </Link>
                  <Link to="/registrati" className="btn btn-primary btn-sm" onClick={closeMenu}>
                    Registrati
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </div>
    </nav>
  )
}
