// frontend/src/components/Avatar.jsx
import { resolveAssetUrl } from '../api'

// Mostra l'immagine avatar se presente, altrimenti l'iniziale dello username.
export default function Avatar({ username, avatarUrl, size = 36 }) {
  const dimension = { width: size, height: size, fontSize: size * 0.45 }
  const src = resolveAssetUrl(avatarUrl)

  if (src) {
    return (
      <img
        src={src}
        alt={username ? `Avatar di ${username}` : 'Avatar'}
        style={{ ...dimension, borderRadius: '50%', objectFit: 'cover', border: '1px solid var(--border)' }}
      />
    )
  }

  return (
    <span
      aria-hidden="true"
      style={{
        ...dimension,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '50%',
        background: 'var(--bg-secondary)',
        border: '1px solid var(--border)',
        color: 'var(--accent)',
        fontFamily: 'var(--font-mono)',
        fontWeight: 700,
      }}
    >
      {(username || '?').charAt(0).toUpperCase()}
    </span>
  )
}

// frontend/src/app/shared/avatar/avatar.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { resolveAssetUrl } from '../../core/api/api.constants';

@Component({
  selector: 'app-avatar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './avatar.component.html',
})
export class AvatarComponent {
  @Input() username: string | null | undefined = '';
  @Input() avatarUrl: string | null | undefined = null;
  @Input() size = 36;

  get src(): string | null {
    return resolveAssetUrl(this.avatarUrl);
  }

  get initial(): string {
    return (this.username || '?').charAt(0).toUpperCase();
  }

  get dimensionStyle(): Record<string, string> {
    return {
      width: `${this.size}px`,
      height: `${this.size}px`,
      fontSize: `${this.size * 0.45}px`,
    };
  }
}

<img
  *ngIf="src as resolvedSrc"
  [src]="resolvedSrc"
  [alt]="username ? 'Avatar di ' + username : 'Avatar'"
  [ngStyle]="dimensionStyle"
  style="flex-shrink: 0; border-radius: 50%; object-fit: cover; border: 1px solid var(--border);"
/>
<span
  *ngIf="!src"
  aria-hidden="true"
  [ngStyle]="dimensionStyle"
  style="flex-shrink: 0; display: inline-flex; align-items: center; justify-content: center; border-radius: 50%; background: var(--bg-secondary); border: 1px solid var(--border); color: var(--accent); font-family: var(--font-mono); font-weight: 700;"
>{{ initial }}</span>
